apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "rabbitmq:3.9-alpine"
          resources:
            limits:
              memory: "256Mi"
              cpu: "1"
          ports:
            - containerPort: 5672

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq # an available URL for pods' communication (like container name in docker)
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      targetPort: 5672
