version: "3"

services:
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: broker-service.dockerfile
    restart: always # if the image crashes, restart it
    ports:
      - "8080:80" # first port is exposed on the host, second port is exposed on the container
    deploy:
      mode: replicated
      replicas: 1
