name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USER: ${{secrets.DOCKER_USER}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

    steps:
      - uses: actions/checkout@v2

      - name: docker login
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build authentication-service image
        run: |
          cd authentication-service && 
          docker build . -f authentication-service.dockerfile -t $DOCKER_USER/authentication-service:1.0.0

      - name: Push authentication-service image to docker hub
        run: docker push $DOCKER_USER/authentication-service:1.0.0

      - name: Build broker-service image
        run: |
          cd broker-service && 
          docker build . -f broker-service.dockerfile -t $DOCKER_USER/broker-service:1.0.0

      - name: Push broker-service image to docker hub
        run: docker push $DOCKER_USER/broker-service:1.0.0

      - name: Build front-end image
        run: |
          cd front-end && 
          docker build . -f front-end.dockerfile -t $DOCKER_USER/front-end:1.0.1

      - name: Push front-end image to docker hub
        run: docker push $DOCKER_USER/front-end:1.0.1

      - name: Build listener-service image
        run: |
          cd listener-service && 
          docker build . -f listener-service.dockerfile -t $DOCKER_USER/listener-service:1.0.0

      - name: Push listener-service image to docker hub
        run: docker push $DOCKER_USER/listener-service:1.0.0

      - name: Build logger-service image
        run: |
          cd logger-service && 
          docker build . -f logger-service.dockerfile -t $DOCKER_USER/logger-service:1.0.1

      - name: Push logger-service image to docker hub
        run: docker push $DOCKER_USER/logger-service:1.0.1

      - name: Build mail-service image
        run: |
          cd mail-service && 
          docker build . -f mail-service.dockerfile -t $DOCKER_USER/mail-service:1.0.0

      - name: Push mail-service image to docker hub
        run: docker push $DOCKER_USER/mail-service:1.0.0

      - name: Build caddy image
        run: |
          cd project && 
          docker build . -f caddy.dockerfile -t $DOCKER_USER/micro-caddy:1.0.0

      - name: Push caddy image to docker hub
        run: docker push $DOCKER_USER/micro-caddy:1.0.0

      - name: Build caddy (production) image
        run: |
          cd project && 
          docker build . -f caddy.production.dockerfile -t $DOCKER_USER/micro-caddy-production:1.0.1

      - name: Push caddy (production) image to docker hub
        run: docker push $DOCKER_USER/micro-caddy-production:1.0.1
