name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USER: ${{secrets.DOCKER_USER}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      IMAGE_VERSION: ${{secrets.VERSION}}

    steps:
      - uses: actions/checkout@v2

      - name: build go binary
        run: |
          cd project &&
          make up_build

      - name: docker login

        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build authentication-service image
        run: |
          cd authentication-service && 
          docker build . -f authentication-service.dockerfile -t $DOCKER_USER/authentication-service:$IMAGE_VERSION

      - name: Push authentication-service image to docker hub
        run: docker push $DOCKER_USER/authentication-service:$IMAGE_VERSION

      - name: Build broker-service image
        run: |
          cd broker-service && 
          docker build . -f broker-service.dockerfile -t $DOCKER_USER/broker-service:$IMAGE_VERSION

      - name: Push broker-service image to docker hub
        run: docker push $DOCKER_USER/broker-service:$IMAGE_VERSION

      - name: Build front-end image
        run: |
          cd front-end && 
          docker build . -f front-end.dockerfile -t $DOCKER_USER/front-end:$IMAGE_VERSION

      - name: Push front-end image to docker hub
        run: docker push $DOCKER_USER/front-end:$IMAGE_VERSION

      - name: Build listener-service image
        run: |
          cd listener-service && 
          docker build . -f listener-service.dockerfile -t $DOCKER_USER/listener-service:$IMAGE_VERSION

      - name: Push listener-service image to docker hub
        run: docker push $DOCKER_USER/listener-service:$IMAGE_VERSION

      - name: Build logger-service image
        run: |
          cd logger-service && 
          docker build . -f logger-service.dockerfile -t $DOCKER_USER/logger-service:$IMAGE_VERSION

      - name: Push logger-service image to docker hub
        run: docker push $DOCKER_USER/logger-service:$IMAGE_VERSION

      - name: Build mail-service image
        run: |
          cd mail-service && 
          docker build . -f mail-service.dockerfile -t $DOCKER_USER/mail-service:$IMAGE_VERSION

      - name: Push mail-service image to docker hub
        run: docker push $DOCKER_USER/mail-service:$IMAGE_VERSION
